### ISSUE TITLE
Something wrong when simulate python python/gps/gps_main.py mjc_badmm_example.

### ISSUE THREAD

**Issue by nwcora** [cbfinn/gps#101]
i have set the environment of caffe,but when i run this, it occurs 
Traceback (most recent call last):
  File "python/gps/gps_main.py", line 414, in <module>
    main()
  File "python/gps/gps_main.py", line 348, in main
    hyperparams = imp.load_source('hyperparams', hyperparams_file)
  File "/home/wq/gps/experiments/mjc_badmm_example/hyperparams.py", line 19, in <module>
    from gps.algorithm.policy_opt.policy_opt_caffe import PolicyOptCaffe
  File "python/gps/algorithm/policy_opt/policy_opt_caffe.py", line 8, in <module>
    import caffe
  File "python/gps/algorithm/policy_opt/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "python/gps/algorithm/policy_opt/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
ImportError: No module named caffe.io
i see when set ros ,there are something to compile with 
cd src/gps_agent_pkg/
cmake . -DUSE_CAFFE=1 -DCAFFE_INCLUDE_PATH=/path/to/caffe/distribute/include -DCAFFE_LIBRARY_PATH=/path/to/caffe/build/lib
make -j
but there isnt anything to set when set mujoco? so what's my problem?

**Comment by cbfinn** [comment]
It looks like you don't have caffe installed and pycaffe properly enabled, or something changed with the caffe API and you need to use an older version.

As in the docs, make sure that: pycaffe is compiled, python layer enabled, PYTHONPATH configured
