### ISSUE TITLE
 SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'.

### ISSUE THREAD

**Issue by guoyaq** [cbfinn/gps#112]
when I run $python python/gps/gps_main.py pr2_example
here is error:
python/gps/agent/ros/ros_utils.py:106: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self._pub = rospy.Publisher(pub_topic, pub_type)
Traceback (most recent call last):
  File "python/gps/gps_main.py", line 414, in <module>
    main()
  File "python/gps/gps_main.py", line 399, in main
    gps = GPSMain(hyperparams.config, args.quit)
  File "python/gps/gps_main.py", line 49, in __init__
    self.gui = GPSTrainingGUI(config['common']) if config['gui_on'] else None
  File "python/gps/gui/gps_training_gui.py", line 98, in __init__
    self._action_output = Textbox(self._fig, self._gs_action_output, border_on=True)
  File "python/gps/gui/textbox.py", line 41, in __init__
    self.set_bgcolor(bgcolor, bgalpha)  # this must come after fig.canvas.draw()
  File "python/gps/gui/textbox.py", line 65, in set_bgcolor
    self.draw()
  File "python/gps/gui/textbox.py", line 70, in draw
    self._ax.draw_artist(self._ax.patch)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes.py", line 1994, in draw_artist
    assert self._cachedRenderer is not None
AssertionError

please help me

**Comment by dujinyu** [comment]
I have many questions to consult you, can you add QQ 1242642280? @guoyaq
