### ISSUE TITLE
got the "LinAlgError" while run "python python/gps/gps_main.py box2d_badmm_example"

### ISSUE THREAD

**Issue by peterzliang** [cbfinn/gps#31]
Hi,

First, thank a lot for your excellent work. 

I tried to run "python python/gps/gps_main.py box2d_badmm_example". Got the "LinAlgError".
BTW, no problem for me to run "python python/gps/gps_main.py box2d_arm_example"

The output log:

$ python python/gps/gps_main.py box2d_badmm_example
<...SNIP...>
I0615 17:57:23.078760 25761 net.cpp:684] Ignoring source layer Python4
I0615 17:57:23.219300 25761 net.cpp:684] Ignoring source layer Python4
I0615 17:57:24.172405 25761 net.cpp:684] Ignoring source layer Python4
I0615 17:57:24.303740 25761 net.cpp:684] Ignoring source layer Python4
I0615 17:57:28.371433 25761 solver.cpp:337] Iteration 0, Testing net (#0)
I0615 17:57:28.371523 25761 net.cpp:684] Ignoring source layer Python4
I0615 17:57:28.371626 25761 solver.cpp:404]     Test net output #0: InnerProduct3 = -0.000267899
I0615 17:57:28.371691 25761 solver.cpp:404]     Test net output #1: InnerProduct3 = -8.7297e-05
I0615 17:57:28.371724 25761 solver.cpp:337] Iteration 0, Testing net (#1)
I0615 17:57:28.371752 25761 net.cpp:684] Ignoring source layer Python1
I0615 17:57:28.371785 25761 net.cpp:684] Ignoring source layer Python4
I0615 17:57:28.371830 25761 solver.cpp:404]     Test net output #0: InnerProduct3 = 0
I0615 17:57:28.371863 25761 solver.cpp:404]     Test net output #1: InnerProduct3 = 0
I0615 17:57:36.898833 25761 net.cpp:684] Ignoring source layer Python4
I0615 17:57:36.901408 25761 net.cpp:684] Ignoring source layer Python4
I0615 17:57:37.029466 25761 net.cpp:684] Ignoring source layer Python4
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "python/gps/gps_main.py", line 387, in <lambda>
    target=lambda: gps.run(itr_load=resume_training_itr)
  File "python/gps/gps_main.py", line 85, in run
    self._take_iteration(itr, traj_sample_lists)
  File "python/gps/gps_main.py", line 213, in _take_iteration
    self.algorithm.iteration(sample_lists)
  File "python/gps/algorithm/algorithm_badmm.py", line 59, in iteration
    self._update_policy_fit(m)  # Update policy priors.
  File "python/gps/algorithm/algorithm_badmm.py", line 180, in _update_policy_fit
    SampleList(self.cur[m].pol_info.policy_samples)
  File "python/gps/algorithm/policy/policy_prior_gmm.py", line 83, in update
    self.gmm.update(XU, K)
  File "python/gps/utility/gmm.py", line 175, in update
    logobs = self.estep(data)
  File "python/gps/utility/gmm.py", line 76, in estep
    check_finite=False)
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/decomp_cholesky.py", line 81, in cholesky
    check_finite=check_finite)
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/decomp_cholesky.py", line 30, in _cholesky
    raise LinAlgError("%d-th leading minor not positive definite" % info)
LinAlgError: 1-th leading minor not positive definite

Thanks,
Peter

**Comment by peterzliang** [comment]
just read the same issue
https://github.com/cbfinn/gps/issues/24
